[package]
name = "basic-imap"
version = "0.0.0"
authors = ["Matthias Fauconneau <matthias.fauconneau@gmail.com>"]

[dependencies]
imap = { git = "https://github.com/jonhoo/rust-imap.git" }
native-tls = ""
dbus = "^0.7"
nix = ""
mailparse = ""
chrono = ""
notify-rust = ""
